# Generated by Django 5.0.2 on 2025-04-09 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("active_users", models.IntegerField(default=0)),
                ("new_users", models.IntegerField(default=0)),
                ("posts", models.IntegerField(default=0)),
                ("comments", models.IntegerField(default=0)),
                ("likes", models.IntegerField(default=0)),
                ("friendships", models.IntegerField(default=0)),
                ("messages", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Daily Metrics",
                "verbose_name_plural": "Daily Metrics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("post_count", models.IntegerField(default=0)),
                ("comment_count", models.IntegerField(default=0)),
                ("like_count", models.IntegerField(default=0)),
                ("message_count", models.IntegerField(default=0)),
                ("login_count", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Activities",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
