# Generated by Django 5.0.2 on 2025-04-09 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("friends", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="friendship",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Friendship",
                "verbose_name_plural": "Friendships",
            },
        ),
    ]
