# Generated by Django 5.0.2 on 2025-04-10 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_mobile_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="mobile_number",
            field=models.CharField(
                help_text="Enter a valid 10-digit mobile number starting with 6-9",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Mobile number must be 10 digits long and start with 6-9",
                        regex="^[6-9]\\d{9}$",
                    )
                ],
            ),
        ),
    ]
